### ISSUE TITLE
CRPD-all unzip failed

### ISSUE THREAD

**Issue by tycallen** [yxgong0/CRPD#2]
![Xnip2022-05-17_11-30-33](https://user-images.githubusercontent.com/3022000/168723030-fd1c5551-7978-4d2f-93e0-4d6c2b7601e8.jpg)

**Comment by tangsipeng** [comment]
zip -F CRPD_all.zip --out all.zip
unzip all.zip

**Comment by tycallen** [comment]
thanks!
